### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by aslafy-z** [Tufin/pytos#30]
Hello,

Is this package still maintained?
I see there are multiple issues and PR opened with no reaction from maintainers.
Also, it should be refactored to use the JSON endpoints.

Can you update us on that?

Thanks,

**Comment by ramiaviad** [comment]
Hello, 
referring to your question this package is maintainable and we are going to address the pull requests.
However, 
please keep in mind it is a public channel so not all Tufin features are supported here. 
You are more than welcomed to extend the package capabilities, we'll be happy to assist with any question.
thanks,
Rami.
