### ISSUE TITLE
Usage of inotify

### ISSUE THREAD

**Issue by PaulNokel** [Tufin/pytos#7]
You are using inotify for some log handling actions. However, inotify is not available on MacOS, it is Linux only. I would like to use pytos directly on my workstation for some presentations and basic development. Is it possible to replace inotify as a dependency and replace it with something that is available on more platforms?

Best regards,
Paul

**Comment by packetinspector** [comment]
Same issue.  I can not utilized pytos on OSX.

**Comment by ShayHaluba** [comment]
Same issue on Win 7 :(

**Comment by funkycode** [comment]
As Tufin applications would not run on MacOS or Windows - we currently do not support it (not aware if we ever would).
I would suggest to setup IDE to run and debug it from your OS remotely on the TOS server.

See the example on how you can use pycharm for that:
https://www.jetbrains.com/help/pycharm/remote-debugging.html

**Comment by packetinspector** [comment]
Why would it matter where you run the application?   Are you saying APIs only work on linux in general?  

I think it's prudent to remove the dependency so more people can make use of Pytos.

**Comment by funkycode** [comment]
Again - this is not planned.
Moreover there are other 3rd party libs we use and we are not going to support it partially so it works only in specific cases, which in this case do cover your needs.

If you use pytos - you need ST or SC. So use them and setup remote config with IDE - it's acceptable way most development works.
