### ISSUE TITLE
get_network_object_by_device_and_object_id() returns wrong network object

### ISSUE THREAD

**Issue by packetinspector** [Tufin/pytos#8]
The Tufin API will return group members along with the group, so the logic in the function:

`network_object = Network_Objects_List.from_xml_string(response_string)[0]`

is not valid.  The list needs to be searched for the requested ID and then returned instead.  For example:

`for n in Network_Objects_List.from_xml_string(response_string):
                 if n.id == network_object_id:
                    network_object = n
                    break`

**Comment by tgratzi** [comment]
Added
